<?php
/**
 * @file
 * Install, update and uninstall functions for the vrausbildungsboerse_profile installation profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function <%= profileMachineName %>_install() {
  \Drupal::configFactory()->getEditable('system.site')
    // Set site slogan.
    ->set('slogan', 'Slogan')
    // Set front page.
    //->set('page.front', '')
    ->save(TRUE);
}
